version: '3.9'

services:
  db:
    image: postgres:16
    container_name: myservice-postgres
    environment:
      POSTGRES_DB: notes_db
      POSTGRES_USER: notes_db
      POSTGRES_PASSWORD: notes_db
    ports:
      - "5430:5432"
