version: '3.9'

services:
  db:
    image: postgres:16
    container_name: grades_db
    environment:
      POSTGRES_DB: grades_db
      POSTGRES_USER: grades_db
      POSTGRES_PASSWORD: grades_db
    ports:
      - "5430:5432"
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"  # Jaeger UI
      - "14250:14250"  # gRPC
      - "14268:14268"  # HTTP
      - "4317:4317"    # OTLP gRPC
      - "4318:4318"    # OTLP HTTP
      - "6831:6831/udp"  # UDP
      - "6832:6832/udp"  # UDP
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - appz-network

networks:
  appz-network:
    driver: bridge