spring:
  application:
    name: appz-lab02

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  datasource:
    url: jdbc:postgresql://localhost:5434/grades_db
    username: ${DB_USERNAME:grades_db}
    password: ${DB_PASSWORD:grades_db}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: true
    show-sql: false

rabbitmq:
  exchange:
    name: appz-exchange
  queue:
    log: log-queue
    notification: notification-queue
  routing-key:
    log: log-routing-key
    notification: notification-routing-key